Fix width of vertical bar of cursor on double-width chars
equalsraf/neovim-qt pull request #801
Opened 2020-12-21 16:34 UTC by statiolake

Closes #800.

2020-12-21 17:16 UTC, jgehrig commented
@statiolake Nice work finding this bug!

I also noticed this behavior, but assumed it was how things are supposed to work: X% of cursor width -> X% of double-width cell.

Based on observations from `gVim`, you are correct. The statement above is not true for `ver` (vertical bar) cursors.

I believe a simpler code-fix exists:
```
case Cursor::Shape::Vertical:
{
	// Issue #800: Double width characters change the size of cursorRect.
	// Vertical cursors should be based on the cell size only. A double wide
	// character should not have a double wide vertical (insert mode) cursor.
	const QRect cursorRectVertical{ cursorRect.topLeft(), m_cellSize };
	cursorRect.setWidth(cursorRectVertical.width() * m_cursor.GetPercentage() / 100);
}
```

This should be the same calculation and approach, but this shouldn't require any function signature changes. We should avoid adding new function parameters if possible.

Feel free to tweak the snippet above as you see fit, comment or code. Proof of concept with quick testing only.

Can you please fix this without adding `int charWidth` to function calls? Thanks!

2020-12-21 17:20 UTC, jgehrig requested changes
Let's avoid adding the `charWidth` parameter. Keeping the code as simple as possible will be better in the long run.

Also, I think only 2 characters widths are possible: single and double. If we absolutely must add this parameter, lets make it something like `bool isDoubleWidth`.

2020-12-21 18:07 UTC, statiolake commented
> I believe a simpler code-fix exists:

That's a nice idea, I'll fix it soon. Thank you for pointing it out!

2020-12-22 03:05 UTC, merged

2020-12-22 03:05 UTC, jgehrig commented
Two heads are better than one! It improved with each iteration. 

Merged, thanks for the PR :+1: